// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.RecipeHaven.Data.Models;

public partial class NutritionInfo
{
    public int NutritionInfoId { get; set; }

    public double? Calories { get; set; }

    public double? Protein { get; set; }

    public double? Fat { get; set; }

    public double? Carbs { get; set; }

    public double? Fiber { get; set; }

    public double? Sugar { get; set; }

    public bool? ActiveStatus { get; set; }

    public virtual ICollection<Ingredient> Ingredients { get; set; } = new List<Ingredient>();

    public virtual ICollection<Ingredient> IngredientsNavigation { get; set; } = new List<Ingredient>();
}