// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.RecipeHaven.Data.Models;

public partial class Origin
{
    public int OriginId { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    public string CultureDescription { get; set; }

    public bool? ActiveStatus { get; set; }

    public virtual ICollection<Recipe> Recipes { get; set; } = new List<Recipe>();
}