// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.RecipeHaven.Data.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Role { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? ViewedRecipe { get; set; }

    public bool? ActiveStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Recipe> Recipes { get; set; } = new List<Recipe>();

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}