// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD.RecipeHaven.Data.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? ActiveStatus { get; set; }

    public virtual ICollection<Recipe> Recipes { get; set; } = new List<Recipe>();
}